products = [
    ('big bottle coke','60cl coke'),
    ('big bottle fanta','60cl fanta'),
    ('big bottle sprite','60cl sprite'),
    ('small pet coke','35cl coke'),
    ('small pet fanta','35cl fanta'),
    ('small pet sprite','35cl sprite'),
    ('lucuzade', 'lucuzade'),
    ('big pulpy', 'big pulpy'),
    ('small pulpy', 'small pulpy'),
    ('big lacasera', 'big lacasera'),
    ('small lacasera', 'small lacasera'),
    ('pepsi pet', 'pepsi pet'),
    ('team lemon', 'team lemon'),
    ('limca', 'limca'),
    ('chapman', 'chapman'),
    ('mama coke', 'mama coke'),
    ('berryblast', 'berryblast'),
    ('big eva', 'big eva'),
    ('small eva', 'small eva'),
    ('big algor', '75cl algor'), 
    ('small algor', 'small algor'),
    ('star radlar', 'star radlar'),
    ('fayrouz', 'fayrouz'),
    ('can coke', 'can coke'),
    ('can sprite', 'can sprite'),
    ('dubic malt', 'dubic malt'),
    ('malta guiness', 'malta guiness'),
    ('heineken', 'heineken'),
    ('exotic', 'exotic'),
    ('black bullet', 'black bullet'),
    ('fearless', 'fearless'),
    ('predator', 'predator'),
    ('zero pet', 'zero pet'),
    ('action bitter', 'action bitter'),
    ('coke crate', 'coke crate'),
    ('small crate', 'small crate'),
    ('pepsi crate', 'pepsi crate'),
    ('team soda', 'team soda'), 
    ('nutri milk', 'nutri milk'),
    ('big ice block', 'big ice block'),
    ('big ice block', 'big ice block'),
    ('sachet water', 'pure water'), 
    ('small ice block', 'small ice block'),
    ('big ice block', 'big ice block'),
    ('algor small water', '50cl algor')
]

    #('small pet coke', '35cl pet'),
    #('big pet coke', '50cl pet'),
    #('small bottle coke', '35cl rgb'),
    #('big bottle coke', '60cl rgb'),
    #('small eva water', '75cl eva'),
    #('big eva water', '150cl eva'),
    #('maltina', 'maltina'),
    #('fayrouz', 'fayrouz'),
    #('lacasera', 'lacasera'),
    #('sachet water', 'sachet water'),
    #('small ice block', 'small ice block'),
    #('big ice block', 'big ice block'),
