# Generated by Django 4.0.4 on 2022-05-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product_name', models.CharField(max_length=30)),
                ('quantity_sold', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('total', models.IntegerField()),
                ('note', models.TextField()),
            ],
        ),
    ]
