# Generated by Django 4.0.1 on 2022-07-01 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='sold',
            options={'verbose_name_plural': 'Sold'},
        ),
        migrations.AlterField(
            model_name='sold',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sold',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='sold',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AddField(
            model_name='sold',
            name='products',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.products'),
        ),
    ]
