# Generated by Django 4.0.1 on 2022-07-03 20:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_sold_products_alter_products_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='expiry_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='sold',
            name='products',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sold',
            name='product_name',
            field=models.CharField(max_length=30),
        ),
    ]
